### ISSUE TITLE
Issue with Centos 7.3?

### ISSUE THREAD

**Issue by jsilberm** [retr0h/ansible-etcd#51]
[root@PDC2-SM10-N7 ansible-etcd]# ansible-playbook play

PLAY [all] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [server3]
ok: [server2]
ok: [server1]

TASK [retr0h.etcd : Include Configuration] *******************************************************************************************************************
ok: [server1] => (item=/etc/ansible/roles/retr0h.etcd/vars/RedHat.yml)
ok: [server2] => (item=/etc/ansible/roles/retr0h.etcd/vars/RedHat.yml)
ok: [server3] => (item=/etc/ansible/roles/retr0h.etcd/vars/RedHat.yml)

TASK [retr0h.etcd : Install system dependencies for synchronize] *********************************************************************************************
changed: [server1] => (item=rsync)
ok: [server1] => (item=openssh-clients)
ok: [server1] => (item=openssh-server)
changed: [server2] => (item=rsync)
ok: [server2] => (item=openssh-clients)
ok: [server2] => (item=openssh-server)
changed: [server3] => (item=rsync)
ok: [server3] => (item=openssh-clients)
ok: [server3] => (item=openssh-server)

TASK [retr0h.etcd : Download etcd] ***************************************************************************************************************************
changed: [server3]
changed: [server1]
changed: [server2]

TASK [retr0h.etcd : Unarchive etcd] **************************************************************************************************************************
changed: [server1]
changed: [server2]
changed: [server3]

TASK [retr0h.etcd : Copy binaries from archive into etcd dir] ************************************************************************************************
changed: [server2 -> server2] => (item=etcd)
changed: [server1 -> server1] => (item=etcd)
changed: [server3 -> server3] => (item=etcd)
changed: [server2 -> server2] => (item=etcdctl)
changed: [server3 -> server3] => (item=etcdctl)
changed: [server1 -> server1] => (item=etcdctl)

TASK [retr0h.etcd : Add etcd upstart service] ****************************************************************************************************************
skipping: [server1]
skipping: [server2]
skipping: [server3]

TASK [retr0h.etcd : Add etcd systemd service] ****************************************************************************************************************
fatal: [server3]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'etcd'"}
fatal: [server1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'etcd'"}
fatal: [server2]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'etcd'"}
	to retry, use: --limit @/root/ansible-etcd/play.retry

PLAY RECAP ***************************************************************************************************************************************************
server1                    : ok=6    changed=4    unreachable=0    failed=1
server2                    : ok=6    changed=4    unreachable=0    failed=1
server3                    : ok=6    changed=4    unreachable=0    failed=1

[root@PDC2-SM10-N7 ansible-etcd]# uname -a
Linux PDC2-SM10-N7 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Ralnoc** [comment]
This issue is also manifesting on Ubuntu 16.04.

PLAY [etcd] *******************************************************************************************

TASK [Gathering Facts] *******************************************************************************************
ok: [server1]

TASK [retr0h.etcd : Include Configuration] *******************************************************************************************
ok: [server1] => (item=/home/user/.ansible/roles/retr0h.etcd/vars/Debian.yml)

TASK [retr0h.etcd : Install system dependencies for synchronize] *******************************************************************************************
ok: [server1] => (item=rsync)
ok: [server1] => (item=openssh-server)

TASK [retr0h.etcd : Download etcd] *******************************************************************************************
ok: [server1]

TASK [retr0h.etcd : Unarchive etcd] *******************************************************************************************
skipping: [server1]

TASK [retr0h.etcd : Copy binaries from archive into etcd dir] *******************************************************************************************
ok: [server1 -> server1] => (item=etcd)
ok: [server1 -> server1] => (item=etcdctl)

TASK [retr0h.etcd : Add etcd upstart service] *******************************************************************************************
skipping: [server1]

TASK [retr0h.etcd : Add etcd systemd service] *******************************************************************************************
fatal: [server1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'etcd'"}
        to retry, use: --limit @/opt/admin_tools/playbooks/etcd.retry

PLAY RECAP *******************************************************************************************
server1              : ok=5    changed=0    unreachable=0    failed=1

**Comment by ivan1993spb** [comment]
@jsilberm @Ralnoc in order to resolve this error create host group `etcd`

```
[etcd]
first
second
```

**Comment by retr0h** [comment]
Or change the name of the group defined by `etcd_peers_group`.

**Comment by retr0h** [comment]
Closing as not an issue.
